export const driverData = [
  {
    id: "blackIce460Alpha",
    img: "images/fitting/blackIce460.Webp",
    title: "BLACK ICE 460 α",
    link: "blackIce460Alpha",
    price: "1,400,000",
    src: "images/gtdProduct/blackIce460",
  },
  {
    id: "blackIce460",
    img: "images/fitting/blackIce460.Webp",
    title: "BLACK ICE 460",
    link: "blackIce460",
    price: "1,200,000",
    src: "images/gtdProduct/blackIce460",
  },
  {
    id: "blackIceTheMax",
    img: "images/fitting/blackIceTheMax.Webp",
    title: "BLACK ICE THE MAX",
    link: "blackIceTheMax",
    price: "1,200,000",
    src: "images/gtdProduct/blackIceTheMax",
  },
  {
    id: "GT455Plus2",
    img: "images/fitting/GT455Plus2.Webp",
    title: "GT 455 Plus 2",
    link: "GT455Plus2",
    price: "1,200,000",
    src: "images/gtdProduct/GT455Plus2",
  },
  {
    id: "GT455Angel-C",
    img: "images/fitting/GT455Angel-C.Webp",
    title: "GT 455 Angel-C",
    link: "GT455Angel-C",
    price: "1,200,000",
    src: "images/gtdProduct/GT455Angel-C",
  },
  {
    id: "GT455Alpha",
    img: "images/fitting/GT455Alpha.Webp",
    title: "GT 455 Alpha",
    link: "GT455Alpha",
    price: "1,300,000",
    src: "images/gtdProduct/GT455Alpha",
  },
];
